### ISSUE TITLE
Obtaining the similarity matrix from rooted tree

### ISSUE THREAD

**Issue by Ananya1006** [emmanuelparadis/ape#128]
Hi! I had a small doubt and wanted to confirm if this is okay.
I have a rooted phylogenetic tree (tre) and want to obtain the phylogenetic similarity matrix.
The cophenetic.phylo function returns a dissimilarity matrix. Would this be the correct approach?

library(ape)
dist_matrix <- cophenetic.phylo(tre)
max_distance <- max(dist_matrix)
norm_dist_matrix <- dist_matrix / max_distance  # Normalize the distances
similarity_matrix <- 1 - norm_dist_matrix

**Comment by emmanuelparadis** [comment]
Hi,
Yes that seems correct to me. Of course, the normalization depends on the tree so this similarity measures might not comparable easily among trees.
Emmanuel

**Comment by Ananya1006** [comment]
So if I understand correctly, this might not be a valid rational to compare similarity matrices for multiple trees?
My goal is to check the phylogenetic relatedness for various genera (the tip labels) which the rooted tree already has calculated, based on the main root, i.e. I'm only dealing with one single rooted tree and not multiple trees. 

Thanks for the prompt reply!

**Comment by emmanuelparadis** [comment]
Suppose your tree is something like:

((BIRDS,MAMMALS),INSECTS);

where BIRDS means "many species of birds" and same for MAMMALS and INSECTS. The similarity measures between pairs of birds and/or mammals would not be the same than with another tree like:

(BIRDS,MAMMALS);

So yes the measures would be consistent within a tree.

**Comment by Ananya1006** [comment]
Got it. Thanks for the clarification.
