### ISSUE TITLE
ltt.plot() and ltt.plot.coords() misinterpret extinction events?

### ISSUE THREAD

**Issue by TheoPannetier** [emmanuelparadis/ape#3]
Hi @emmanuelparadis I found this strange behaviour of the LTT tools when a (time)tree contains branches that go extinct before the present

```
> packageVersion("ape")
[1] ‘5.4.1’
> phylo <- ape::read.tree(text = "((A:100,(B:50, C:25):50):50);")
# tip C goes extinct 25 time units before present
> ape::ltt.coplot(phylo)
```
![bug_ape_ltt](https://user-images.githubusercontent.com/34482571/109225200-40864e00-77bd-11eb-8a2c-b240b06171c6.png)

The number of species is overestimated by 1 for entire tree's history.
`ltt.plot.coords` give a different, wrong result:

```
> ltt <- ape::ltt.plot.coords(phylo)
> ltt
     time N
[1,] -150 1
[2,] -100 2
[3,]  -50 3
[4,]  -25 4
[5,]    0 3
```
The extinction event appears to be treated as a speciation event, then the next speciation event is treated as an extinction event.

By contrast, the output for the same tree with C surviving to the present is correct.

```
> phylo <- ape::read.tree(text = "((A:100,(B:50, C:50):50):50);")
> ape::ltt.coplot(phylo)
```
![bug_ape_ltt2](https://user-images.githubusercontent.com/34482571/109225735-fc477d80-77bd-11eb-9c5e-b1572fa01f53.png)

```
> ltt <- ape::ltt.plot.coords(phylo)
> ltt
     time N
[1,] -150 1
[2,] -100 1
[3,]  -50 2
[4,]    0 3
```

**Comment by TheoPannetier** [comment]
Just noticed that the output of `ltt.plot.coords()` for the second tree just above is wrong too - the first speciation event is ignored, while the present is counted as a speciation event.

**Comment by emmanuelparadis** [comment]
Hi Theo,
Thanks for this report. The origin of this problem is that `phylo` includes a singleton node which you can make disappear by removing the most outer pair of parentheses in the Newick string:
```r
R> has.singles(phylo)
[1] TRUE
R> tr <- read.tree(text = "(A:100,(B:50, C:25):50):50;")
R> has.singles(tr)
[1] FALSE
```
`ltt.coplot(tr)` should work as expected. There is a function `collapse.singles` to solve this problem: I'll fix it and push a new version soon. In the meantime you can add the above checks in your scripts.

For your second message, this is as expected because the output of `ltt.plot.coords()` is plotted with `plot(.... type = "S")` (not lowercase 's'). So the second column (`N`) is interpreted like this: the value `ltt[i, 2]`is the number of lineages alive between time `ltt[i - 1, 1]` and time `ltt[i, 1]` (with i > 1) and `ltt[1, 2]` is always 1.

**Comment by TheoPannetier** [comment]
Thanks for the fix! Removing the outer pair of brackets indeed does the trick!
``` r
library(ape)
phylo <- read.tree(text = "(A:100,(B:50, C:25):50):50;")
phylo$root.edge
> 50
ltt.coplot(phylo)
```

![](https://i.imgur.com/0UENz88.png)

Using `collapse.singles()` also fixes the LTT but has the side-effect of cutting the stem:

``` r
phylo <- ape::read.tree(text = "((A:100,(B:50, C:25):50):50);")
phylo2 <- ape::collapse.singles(phylo)
phylo2$root.edge
#> NULL
ape::ltt.coplot(phylo2)
```

![](https://i.imgur.com/vTKi8lg.png)

But I see there is already an argument to fix this:

``` r
phylo2 <- ape::collapse.singles(phylo, root.edge = TRUE)
phylo2$root.edge
#> [1] 50
ape::ltt.coplot(phylo2)
```

![](https://i.imgur.com/ZCcDKgB.png)

<sup>Created on 2021-02-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by TheoPannetier** [comment]
> For your second message, this is as expected because the output of ltt.plot.coords() is plotted with plot(.... type = "S") (not lowercase 's'). So the second column (N) is interpreted like this: the value ltt[i, 2]is the number of lineages alive between time ltt[i - 1, 1] and time ltt[i, 1] (with i > 1) and ltt[1, 2] is always 1.

I just noticed this is described in the documentation of the function, apologies for missing that!
I find it quite unintuitive to read the output that way: to find the number of lineages alive at t= -100 for example, I should look at the value of `N` in the row corresponding to `t = -50` – though I acknowledge this is a matter of personal taste.
Could the type of output given by `ltt.plot.coords()` be made an argument of the function? That should be straightforward to do (shift column `N` up one step if `type = "s"` and pass the value of the argument from `ltt.plot()` to `ltt.plot.coords()` and base `plot()`). 

I'd be happy to implement this if you think this is a sound suggestion!

**Comment by emmanuelparadis** [comment]
I see your point. The N's may actually be interpreted as "number" of lineages between two time points estimated from the node ages. So it could be said that there are N=2 or that N=3 in your last plot. Do you mean to leave to the user to choose between these two? This is a bit similar to the issue of calculating histogram frequencies with a continuous distribution: both `hist()` and `cut()` have an the `include.lowest` for this.

**Comment by TheoPannetier** [comment]
> Do you mean to leave to the user to choose between these two?

Yes this is what I meant 🙂 
I have proposed an implementation in #5

Otherwise thanks for the new line in ba6507d536f39c08240428b5b8f9c7b92303d67f, this seems to work wonders!

**Comment by TheoPannetier** [comment]
Problem solved then, let's close the issue 👍
