### ISSUE TITLE
can't read in tree

### ISSUE THREAD

**Issue by lpipes** [emmanuelparadis/ape#58]
This seems to be hanging here
```
tree<-read.tree("global.tree")
```
But I can't attach the file here because the tree is too big. Compressed it's ~28MB.

**Comment by HedvigS** [comment]
Dear @lpipes . It is going to be very difficult to help unless we know more. What format the tree is in. Is it newick?

Can you upload it somewhere and provide a link to it here?

**Comment by lpipes** [comment]
The program finally read the tree in. I think it's just a very big file. Thanks!

**Comment by HedvigS** [comment]
@lpipes wonderful!
