### ISSUE TITLE
segfault when reading in tree

### ISSUE THREAD

**Issue by lpipes** [emmanuelparadis/ape#70]
Hi, I have this tree and it segfaults every time I try read.tree()

```
library(ape)
tree<-read.tree("tree.txt")
```

[tree.txt](https://github.com/emmanuelparadis/ape/files/10830052/tree.txt)

**Comment by emmanuelparadis** [comment]
Hi, The bug is in the C file `tree_build.c`: the array `stack_internal` is too small for your tree (it's 10000 and cannot be changed unless recompiling). It can be increased to 100000 and your tree can be read.
I'll push a fix in a moment.
Cheers,

**Comment by emmanuelparadis** [comment]
Fixed and pushed.
