### ISSUE TITLE
Cannot install ape in RStudio

### ISSUE THREAD

**Issue by strawberry098** [emmanuelparadis/ape#89]
I cannot install ape upon downloading `ape_5.7-1.zip` to windows and installing in RStudio 2023.03.0 by `install.packages("C:/Users/jtse02/Downloads/ape_5.7-1.zip", repos = NULL, type = "win.binary")`

Output was:
`package 'ape' successfully unpacked and MD5 sums checked
Error in install.packages : package 'ape' not installed because it is not built for UCRT`

**Comment by emmanuelparadis** [comment]
I have no idea how to help you (I don't use Rstudio and neither Windows). Maybe you should ask on a Rstudio-related forum.
